// ============================================================
// Blends prontos (por intenção) — dados, sem comportamento
// ============================================================
// Saiu de js/app.js no PR 10 do handoff porque tem dois leitores: o app e
// scripts/prerender.mjs, que gera /blends/<slug>/ a partir dos mesmos dados,
// sem navegador. Script clássico sem dependência, como js/herbs-data.js,
// js/fichas-data.js e js/nav-data.js.
// ============================================================
// A chave é a intenção em português (a mesma que INTENCOES[].blend aponta);
// `default` é o blend de «Me ajuda a escolher».
const BLEND_DB = {
  'Insônia':{ name:'Infusão do Silêncio', tagline:'Serenidade profunda para noites difíceis',
    ings:[{id:1,n:'Camomila',amount:'1 col. sopa cheia'},{id:3,n:'Maracujá',amount:'1 col. sopa'},{id:4,n:'Melissa',amount:'1 col. sopa'}],
    steps:['Ferva a água até 85°C (não ferver muito).','Misture as ervas numa infusora.','Cubra e deixe em infusão por 10 minutos.','Coe e beba morno, 40 min antes de dormir.','Evite telas e luzes fortes após tomar.'],
    effects:['Sedação suave','Reduz ruminação mental','Sem dependência'],
    obs:'Potencialize com aromaterapia de lavanda no quarto.' },
  'Ansiedade':{ name:'Blend da Calma Profunda', tagline:'Para momentos de tensão e nervosismo',
    ings:[{id:3,n:'Maracujá',amount:'2 col. sopa'},{id:13,n:'Alfazema',amount:'1 col. sopa flores'},{id:4,n:'Melissa',amount:'1 col. sopa'}],
    steps:['Aqueça água a 85°C.','Adicione as ervas e cubra bem.','Infusão de 8-10 minutos.','Coe, adicione mel se desejar.','Beba lentamente, respirando fundo.'],
    effects:['Ansiolítico natural','Sem sonolência forte','Ação em 20-30 min'],
    obs:'Use 2-3x ao dia em períodos de estresse intenso.' },
  'Dor de estômago':{ name:'Elixir do Conforto Gástrico', tagline:'Alívio suave e aromático para o estômago',
    ings:[{id:1,n:'Camomila',amount:'1 col. sopa cheia'},{id:9,n:'Hortelã',amount:'1 col. sopa'},{id:10,n:'Erva-doce',amount:'1/2 col. sopa'}],
    steps:['Ferva água a 90°C.','Junte as três ervas juntas.','Cubra e infuse por 8 minutos.','Coe e beba morno em pequenos goles.','Deite de lado direito após tomar.'],
    effects:['Antiespasmódico','Alivia gases e cólicas','Anti-inflamatório da mucosa'],
    obs:'Para gastrite: substituir hortelã por espinheira santa.' },
  'Gases':{ name:'Blend Carminativo', tagline:'Liberte os gases e alivie o desconforto',
    ings:[{id:10,n:'Erva-doce',amount:'1 col. sopa'},{id:9,n:'Hortelã',amount:'1 col. sopa'},{id:11,n:'Canela',amount:'1 pedaço pequeno'}],
    steps:['Aqueça a 90°C.','Junte as ervas.','Infusão coberta por 7 minutos.','Coe e beba ainda quente.','Massageie a barriga em círculos.'],
    effects:['Carminativo potente','Relaxa musculatura intestinal','Efeito em 15-20 min'],
    obs:'Excelente após refeições com leguminosas.' },
  'Estresse':{ name:'Chai da Serenidade', tagline:'Conforto quente para dias pesados',
    ings:[{id:19,n:'Erva Cidreira',amount:'2 col. sopa'},{id:17,n:'Capim-Limão',amount:'2 folhas frescas'},{id:1,n:'Camomila',amount:'1 col. sopa'}],
    steps:['Ferva água a 88°C.','Amasse levemente o capim-limão antes.','Infuse coberto por 8 minutos.','Adicione mel a gosto.','Beba com calma, longe das telas.'],
    effects:['Reduz cortisol','Calmante sem sedação','Aroma terapêutico'],
    obs:'Combine com 5 minutos de respiração lenta.' },
  'Foco':{ name:'Poção do Foco Profundo', tagline:'Clareza mental e concentração sustentada',
    ings:[{id:6,n:'Chá Verde',amount:'1 col. sopa'},{id:8,n:'Alecrim',amount:'1 col. sopa'},{id:11,n:'Canela',amount:'1/2 col. chá'}],
    steps:['Aqueça água a 75°C (não ferver).','Junte as ervas.','Infusão curta: 4 minutos apenas.','Coe e beba morno.','Tomar 30 min antes de estudar ou trabalhar.'],
    effects:['L-teanina + cafeína: foco calmo','Sem ansiedade','Melhora memória de trabalho'],
    obs:'Ideal pela manhã. Evitar após 15h.' },
  'Cansaço':{ name:'Tônico Revigorante', tagline:'Energia limpa e sustentada para o dia',
    ings:[{id:5,n:'Gengibre',amount:'4 fatias frescas'},{id:11,n:'Canela',amount:'1 pau pequeno'},{id:17,n:'Capim-Limão',amount:'2 folhas'}],
    steps:['Ferva água a 95°C.','Adicione gengibre e canela primeiro.','Cozinhe por 5 minutos em fogo baixo.','Desligue, adicione capim-limão.','Infuse tampado por 5 min. Coe.'],
    effects:['Termogênico','Circulação ativa','Energia sem pico'],
    obs:'Com raspas de limão e mel: sabor excepcional.' },
  'Gripe/Tosse':{ name:'Antigripal Poderoso', tagline:'Combate a gripe com força da natureza',
    ings:[{id:5,n:'Gengibre',amount:'5 fatias frescas'},{id:16,n:'Guaco',amount:'2 col. sopa'},{id:28,n:'Tomilho',amount:'1 col. sopa'}],
    steps:['Ferva água a 100°C.','Adicione todas as ervas.','Infusão coberta por 12 minutos.','Coe, adicione mel + limão.','Tomar 3-4x ao dia na fase aguda.'],
    effects:['Broncodilatador','Expectorante','Antiviral natural'],
    obs:'Potencializar com inalação de vapor de eucalipto.' },
  'Emagrecimento':{ name:'Blend Queima-Gordura', tagline:'Acelera o metabolismo de forma natural',
    ings:[{id:6,n:'Chá Verde',amount:'1 col. sopa'},{id:21,n:'Carqueja',amount:'1 col. sopa'},{id:7,n:'Hibisco',amount:'1 col. sopa'}],
    steps:['Aqueça água a 80°C.','Misture as três ervas.','Infusão de 5-7 minutos.','Coe e beba sem adoçar.','Tomar 30 min antes das refeições.'],
    effects:['Termogênico','Inibe absorção de carboidratos','Diurético suave'],
    obs:'Associar com caminhada de 30 min diários.' },
  'Pressão alta':{ name:'Infusão Hipotensora', tagline:'Apoio natural para pressão equilibrada',
    ings:[{id:7,n:'Hibisco',amount:'2 col. sopa'},{id:4,n:'Melissa',amount:'1 col. sopa'},{id:17,n:'Capim-Limão',amount:'2 folhas'}],
    steps:['Ferva água a 90°C.','Adicione as ervas.','Infusão coberta por 10 minutos.','Coe e beba sem adoçar (mel mínimo).','3 xícaras ao dia por 6+ semanas.'],
    effects:['Hipotensor suave','Vasodilatador','Ansiolítico complementar'],
    obs:'NÃO substituir medicação. Monitorar PA regularmente.' },
  'TPM':{ name:'Blend da Lua', tagline:'Conforto e equilíbrio no período menstrual',
    ings:[{id:1,n:'Camomila',amount:'2 col. sopa'},{id:4,n:'Melissa',amount:'1 col. sopa'},{id:10,n:'Erva-doce',amount:'1 col. sopa'}],
    steps:['Ferva água a 88°C.','Misture as ervas com carinho.','Infusão de 10 minutos coberta.','Adicione mel e canela a gosto.','3x ao dia nos dias de maior desconforto.'],
    effects:['Antiespasmódico uterino','Alivia irritabilidade','Anti-inflamatório'],
    obs:'Adicionar folha de amora para menopausa.' },
  'default':{ name:'Blend Equilibrante', tagline:'Harmonia e bem-estar para o dia a dia',
    ings:[{id:19,n:'Erva Cidreira',amount:'2 col. sopa'},{id:17,n:'Capim-Limão',amount:'2 folhas'},{id:5,n:'Gengibre',amount:'2 fatias'}],
    steps:['Ferva água a 88°C.','Junte as ervas.','Infusão coberta por 8 minutos.','Coe e personalize com mel ou limão.'],
    effects:['Equilíbrio geral','Digestivo','Calmante suave'],
    obs:'Ajuste as proporções ao seu gosto e necessidade.' },
};
